apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simplenotes-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.host | default "simplenotes.com" }}
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: simplenotes-backend
            port:
              number: 5001
      - path: /api(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: frontend-service
            port:
              number: 80
