apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: simplenotes-backend-monitor
  namespace: app
  labels:
    release: my-kube-prometheus 
spec:
  namespaceSelector:
    matchNames:
    - app
  selector:
    matchLabels:
      app: backend
  endpoints:
  - port: http
    path: /metrics
    interval: 15s