
name: Backend CI/CD

on:
  push:
    branches:
      - master
    paths:
      - 'simplenotes/backend/**'

jobs:
  build:
    name: Install & setup Python dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: ./simplenotes/backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      - uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          projectBaseDir: simplenotes/backend

  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./simplenotes/backend
          file: ./simplenotes/backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/simplenotes-backend:${{ github.run_id }}

  update-newtag-in-helm:
    name: Update Helm Chart
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_PAT }}

      - name: Update new tag in Helm chart
        run: |
          sed -i '/simplenotes-backend/!b;n;s/tag: .*/tag: "${{ github.run_id }}"/' helm/simplenotes-app-chart/values.yaml

      - name: Commit and push changes
        run: |
          git config --local user.email "ariefshaik001@gmail.com"
          git config --local user.name "ariefshaik7"
          git add helm/simplenotes-app-chart/values.yaml
          git commit -m "ci: update backend image tag to ${{ github.run_id }}"
          git push

